/// <reference lib="webworker" />
import { skipWaiting, clientsClaim } from "workbox-core";
import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate } from "workbox-strategies";

declare const self: ServiceWorkerGlobalScope;

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Skip the waiting phase
skipWaiting();

// Claim the clients
clientsClaim();

// Use stale-while-revalidate strategy for API requests to TMDB
registerRoute(
  ({ url }) => url.origin === "https://api.themoviedb.org",
  new StaleWhileRevalidate()
);
